### ISSUE TITLE
Channel closed after exlusive consume (on 2nd worker)

### ISSUE THREAD

**Issue by ovr** [php-amqplib/php-amqplib#434]
Hey!

If you are going to consume queue with $exclusive = true on the second worker
It's going to throw an Exception (AMQPProtocolChannelException) and channel is going to close
Code: 403

Main question:

Is it okey? I think channel not needed to be closed, only exception

Another question:
- How to understand is queue locked by exclusive locked or not to prevent related Exception

Thanks

**Comment by hairyhum** [comment]
Closing a channel with an exception is the way to notify a client about the exception. You can think of it as an exception on the protocol level.
If you use predefined queue name - you should be ready to handle channel exceptions. Otherwise, you can use auto-generated queue names by using an empty queue name in `queue.declare` and get the queue name from `declare-ok`.
