### ISSUE TITLE
Does it make sense to be using TCP's keepalive and Rabbitmq's heartbeat at the same time?

### ISSUE THREAD

**Issue by d-ph** [php-amqplib/php-amqplib#461]
Hi,

Does it make sense to be using TCP's keepalive and Rabbitmq's heartbeat at the same time? They both solve the same problem (checking, whether the connection is still established) but with different means (tcp on protocol level and rabbitmq on application level). 

Am I missing something or it doesn't make sense to use those two features at the same time? Since both use "heartbeats" to ensure the connection is still up, having those two running at the same time just adds to the network io unnecessarily, right?

Thanks.

**Comment by michaelklishin** [comment]
TCP keepalive's goal is to *maintain* a TCP connection for a long as possible, assuming issues are transient.

[Heartbeats' goal](http://www.rabbitmq.com/heartbeats.html) is to *detect peer unavailability* as soon as possible, because with TCP keepalive and default Linux settings it can take over 30 minutes by default (yes, 30 minutes).

**Comment by michaelklishin** [comment]
A heartbeat frame is 8 bytes IIRC and is sent no more than 24 times a minute (we recommend against timeout values lower than 5 seconds since they are likely to cause false positives). If saving that much traffic is more important than detecting connectivity issues early, you can disable heartbeats. I wouldn't do it.

**Comment by d-ph** [comment]
Ok, thanks for your reply.

I'm pretty worried about using rabbit's heartbeat because of the issue described in https://github.com/php-amqplib/RabbitMqBundle/issues/301

But I agree, that having no connection status checking is a poor idea.

What I plan to do is to have my workers running up to a certain amount of time (30 minutes), after which they should finish what they're doing and quit or be timeout'd from the synchronous `->wait()` call. I might submit some PRs, because the `idle_timeout` is not quite what I need (I need dynamic idle timeout).

Thanks again.

**Comment by MakarMS** [comment]
> TCP keepalive's goal is to _maintain_ a TCP connection for a long as possible, assuming issues are transient.
> 
> [Heartbeats' goal](http://www.rabbitmq.com/heartbeats.html) is to _detect peer unavailability_ as soon as possible, because with TCP keepalive and default Linux settings it can take over 30 minutes by default (yes, 30 minutes).

Hi. Why can't it be tuned at rabbitmq level to an adequate frequency?
