### ISSUE TITLE
Connection count tenfolds when using $channel->confirm_select() 

### ISSUE THREAD

**Issue by tlamy** [php-amqplib/php-amqplib#495]
We have a long-running producer process.
Pseudo code:
```php
while($event = receiveEvent()) {
  $channel = $this->connection->channel();
  $channel->confirm_select();
  $message = new AMQPMessage($event->getWorkload());
  $channel->basic_publish($message, '', $queueName);
}
```
Before we used AMQPChannel::confirm_select(), we had around 300-400 connections to each rabbit node. After enabling confirm_select(), there are around 3000-4000 connections to each node.

Neither connection nor channel handling code was changed, so I suspect the error in AMQPlib

**Comment by michaelklishin** [comment]
Sorry but unless a way to reproduce is provided, I don't see how
channel settings cannot result in new connections being opened or old one being not closed. See [Heartbeats](http://www.rabbitmq.com/heartbeats.html) and the [TCP keepalive section in the Networking guide](http://www.rabbitmq.com/networking.html).

Some notes on the snippet posted:

 * Opening a new channel per operation, especially with confirms, is very inefficient since you have 2 network round trips per message.

 * Your code publishes but never [waits for confirms to arrive](https://github.com/php-amqplib/php-amqplib/blob/master/demo/amqp_publisher_with_confirms.php#L52). Is this handled outside of the loop or it actually never happens?
