### ISSUE TITLE
Default heartbeat settings

### ISSUE THREAD

**Issue by emil-nasso** [php-amqplib/php-amqplib#563]
The default value for heartbeats in all types of connections is `0`. This disables heartbeats, which is not recommended and could cause dropped connections caused by the os or load balancers in the path of the connection.

The RabbitMQ documentation (https://www.rabbitmq.com/heartbeats.html ) has this to say on the matter: 

> Heartbeats can be disabled by setting the timeout interval to 0. This is not a recommended practice.

> Heartbeat timeouts from 10 to 30 seconds will produce periodic network traffic often enough (roughly every 5 to 15 seconds)) to satisfy defaults of most proxy tools and load balancers. Also see the section on low timeouts and false positives above.

I suggest setting the default `heartbeat` to `15` instead of `0`.

This would also require the default value of `read_write_timeout` to be changed.

Is there any reasoning behind disabling heartbeats that i am missing?

**Comment by decrypted** [comment]
There is at least this problem https://github.com/php-amqplib/php-amqplib/issues/508 ;)

**Comment by skeets23** [comment]
I was also extremely puzzled about the "heartbeat" being disabled by default. Spent quite a bit of time looking for how to turn it on / if it was possible to turn on. Since it wasn't mentioned in the ReadMe at all and wasn't turned on by default, I was starting to think it wasn't even possible.

Then, after finding it was the 14th (final) parameter of the AMQPStreamConnection constructor, I added a non-zero heartbeat, and instantly my Rabbit consumer zombie infestation was cured.

Seriously, is there a reason that the heartbeat parameter is so inaccessible (14th parameter in a sea of optional parameters) AND default to off?? From the RabbitMQ documentation, it seems very clear that turning it off is a very bad idea.

The villagers living in my servers connecting to RabbitMQ would agree, as they were regularly attacked by hoards of RabbitMQ consumer zombies. (messages were regularly being "eaten" by zombie consumers)

Humor aside, it seems the code for this project assumes you'll never need to use the heartbeat function. Is there a "preferred" way of dealing with the zombie hoards that will inevitably follow?

The way I understand it, without a heartbeat, anytime the consumer process ends unexpectedly a new zombie consumer emerges and wrecks havoc on the surrounding villagers.

**Comment by lukebakken** [comment]
Please take the time to review #648 as well as test the upcoming `2.9.0-rc1` release. Thank you.

**Comment by lukebakken** [comment]
> Is there any reasoning behind disabling heartbeats that i am missing?

Yes, because long-running tasks block all I/O in this library. If the task takes longer than the heartbeat timeout, RabbitMQ closes the connection. This proved to be confusing enough for users that at some point in the past, heartbeats were disabled.

**Comment by DiegoWtf** [comment]
Hi, guys.
After upgrading to 2.9.0 i have a lot of errors like this:
Stack trace:
```
#0 /home/../vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php(243): PhpAmqpLib\Wire\IO\AbstractIO->cleanup_error_handler()
#1 /home/../vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(361): PhpAmqpLib\Wire\IO\StreamIO->write('\x01\x00\x01\x00\x00\x00\r\x00<\x00P\x00\x00\x00\x00...')
#2 /home/../vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(485): PhpAmqpLib\Connection\AbstractConnection->write('\x01\x00\x01\x00\x00\x00\r\x00<\x00P\x00\x00\x00\x00...')
#3 /home/../vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(242): PhpAmqpLib\Connection\AbstractConnection->send_channel_method_frame(1, Array, Object(PhpAmqpLib\Wire\AMQPWriter))
#4 /ho in /home/../vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php on line 256
PHP Fatal error:  Uncaught ErrorException: fwrite(): send of 21 bytes failed with errno=104 Соединение разорвано другой стороной in /home/../vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php:242
```

AND

`PHP Fatal error:  Uncaught PhpAmqpLib\Exception\AMQPHeartbeatMissedException: Missed server heartbeat in /home/hb/orders_new/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/AbstractIO.php:140`

Can it be mean that i must to turn off heartbeat or i must search problem in another way?

**Comment by lukebakken** [comment]
@DiegoWtf without seeing your code we could only guess. Your easiest solution is to disable heartbeats by setting the value to `0`.
