### ISSUE TITLE
Workers consuming multiple queues in topic exchange don't always process in parallel prefetch_count=1

### ISSUE THREAD

**Issue by chadszinow** [php-amqplib/php-amqplib#607]
Hi,
I'm getting started with a topic exchange and 2 queues. I have two workers and each worker consumes from both queues with a different callback set per queue. The prefetch_count is 1 so I'm expecting a queue to send a job to either idle worker as soon as the queue has a job.

I have 2 workers running and both idle.

What I am finding odd is I can get into a situation where a job that topic matches both queues gets queued in both but then it gets processed in sequence by the same worker when it could be done in parallel with the two workers. I can then run a job that matches just one queue and then retest the both queue case and it then runs in parallel.

Here is my test case.

[testCase.tar.gz](https://github.com/php-amqplib/php-amqplib/files/2503935/testCase.tar.gz)

The test procedure is start up 2 workers.

```
Console1: php worker.php
Console2: php worker.php
```
Now send a job that matches both queues.
`Console3: php new_start.php queue1.queue2`

I'm not sure of the initial state but I find I can flip between sequential and parallel processing by doing the following once.
`Console3: php new_start.php queue1`

And then doing the following again will operate the opposite way to last run.
`Console3: php new_start.php queue1.queue2`

Is this a valid issue or expected?

**Comment by lukebakken** [comment]
This is pretty interesting. Changing your code to this produces the result you expect:

```
$channel->basic_qos(0, 1, true);
```

I think this is due to using the same channel to consume from two queues, and may have uncovered a bug in RabbitMQ. I'm going to continue investigating.

**Comment by lukebakken** [comment]
Thinking about this some more, there isn't a bug and RabbitMQ is working as intended. The reason you see this behavior is due to using the same channel to consume from two queues.

Each worker sets up two consumers, each with a prefetch of 1 since [`global` is false](https://www.rabbitmq.com/consumer-prefetch.html).

What happens when topic `queue1.queue2` is used two messages are published - one to `queue1` and one to `queue2`. When selecting consumers, either worker is eligible since none have reached their prefetch limit. This it is OK for RabbitMQ to send both messages to the same worker process. You see these messages as being processed sequentially due to the non-threaded nature of PHP.

There's a chance RabbitMQ will make a different selection for workers, but it probably depends on the order in which they are started. Sending more messages over a period of time should see a more even distribution of deliveries.

The fact that publishing a message bound for one queue seems to change RabbitMQ's behavior must be due to how the next consumer is chosen.

So, use global QoS as I describe and you'll get the behavior you want. I hope the linked documentation explains why.

**Comment by chadszinow** [comment]
Thanks for getting back to me.  I'll give your suggested change a go when I can get back to it.

Appreciate your help!
