### ISSUE TITLE
vendor/autoload.php is missing

### ISSUE THREAD

**Issue by ridculy** [php-amqplib/php-amqplib#61]
The vendor/autoload.php is missing on github, it's used in the demo and test.

Could some add this or tell me where I can get this?

**Comment by kennasoft** [comment]
Hi videlalvaro,

I tried using composer... (not too familiar with it). I keep running into the below error whenever I run `composer install`:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package videlalvaro/php-amqplib could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

Below is my composer.json file:
```
{
  "name": "genio/ozinta",
  "description": "Ozinta description",
  "require": {
      "videlalvaro/php-amqplib": "2.4.*"
  }
}
```

Any help would be appreciated, as I don't want to use an alternative means to load the library. Thanks

**Comment by videlalvaro** [comment]
I copy pasted your `composer.json` and ran the commands, everything worked just fine:

```
avidela:test avidela$ composer.phar install
Loading composer repositories with package information
Installing dependencies (including require-dev)
  - Installing videlalvaro/php-amqplib (v2.4.1)
    Downloading: 100%         

Writing lock file
Generating autoload files
avidela:test avidela$ ll
total 16
-rw-r--r--  1 avidela  wheel   132 Jan 25 22:35 composer.json
-rw-r--r--  1 avidela  wheel  2347 Jan 25 22:35 composer.lock
drwxr-xr-x  5 avidela  wheel   170 Jan 25 22:35 vendor/
avidela:test avidela$ ll vendor/
total 8
-rw-r--r--  1 avidela  wheel  183 Jan 25 22:35 autoload.php
drwxr-xr-x  8 avidela  wheel  272 Jan 25 22:35 composer/
drwxr-xr-x  3 avidela  wheel  102 Jan 25 22:35 videlalvaro/
```

**Comment by kennasoft** [comment]
Very strange indeed. One more thing: I'm running this via terminal on a mac. I even tried `sudo composer install`, and got the same error.

**Comment by videlalvaro** [comment]
I'm also running this from a Mac. Maybe ask on the composer mailing list.

**Comment by LMS0815** [comment]
Is there an easy way to run the demo within an windows (IEE) environment?
I really love the API idea, but to get only the example.php  "running" within a IEE environment seems to be impossible without installing all PHP developer tools. 

Unfortunately the 'SplClassLoader.php' Trick is not working foe me.

ERROR: Class 'Bubelbub\SmartHomePHP\SmartHome' not found in C:\WebApps\SmartHome\index.php

**Comment by ngthgiang92** [comment]
<a href="/giang.html">a</a>

**Comment by Creased** [comment]
Obviously, it's too late for the initial issuer but I've solved this issue by running ```php /usr/sbin/composer.phar install -vvv -o``` inside the project folder, IMO the argument "-o" omitted in first installation is necessary for some installations ...

composer.json:
{
	"name": "root/project",
	"description": "DESCRIPTION",
	"authors": [
		{
			"name": "Firstname LASTNAME",
			"email": "contact@domain.tld",
			"homepage": "http://www.domain.tld/",
			"role": "Developer"
		}
	],
	"autoload": {
		"psr-4": {
			"App\\": "application"
		}
	},
	"require": {}
}

**Comment by troindx** [comment]
Hi, I just want to add one tiny thing.

I Hate composer, composer is probably the worst thing ever invented. I get the idea is good but by far the only thing i've suffered with composer is delays and more delays. I spent 2 straight days trying to figure out why composer couldn't install a dependency on my mac. I get that composer can help you to organise things and as a dependency manager it doesn't go that much far off. But when composer fucks up (and it will eventually do) it fucks up for good. Libraries that depend on one place and that are installed on some other place but that are not compatible because two different libraries use different versions of a third library and cant coexist between them....

let me tell you. I hate composer , I ran into this very same problem and i've discovered that I needed to use composer to install certain libraries .

Not only i am not going to use composer, i'm going to have to switch from PHPMailer to some other library that does the same trick because of this very same issue.

I hope you are happy.....
![fad](https://cloud.githubusercontent.com/assets/3263966/11902246/b86b63fe-a5b0-11e5-835f-46d8a650be65.jpg)

**Comment by troindx** [comment]
One friend of mine used composer for a few years and the other day he was diagnosed with cancer.
that's how bad composer is.

Now, back to constructiveness , I get the very same 

Warning: require(vendor/autoload.php): failed to open stream: No such file or directory in  blablabla

I don't want to use composer because I firmly believe that composer will give me cancer in the anus. But I REALLY REALLY REALLY REALLY like PHPMailer. PHPMailer is nice, cute and atractive and will not give me cancer in the anus. I don't understand about autoloaders and things like that. I just want to know how to , without using composer, in a simple way, add that vendor/blabla thing to my project, more like a drag and drop solution, just place the necessary files in the folder, make it work and move on.

can anyone help me? thank you.

**Comment by g012** [comment]
I also don't see the point of providing a zip/tar file for download WITHOUT that file. Doesn't make sense.

**Comment by ridculy** [comment]
it doen't make sense to provide this file. It's from composer and uses a
 auto generated feature.

On Sat, Mar 12, 2016 at 10:43 PM, g012 <notifications@github.com> wrote:

> I also don't see the point of providing a zip/tar file for download
> WITHOUT that file. Doesn't make sense.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/php-amqplib/php-amqplib/issues/61#issuecomment-195812511>
> .
>



-- 
Mit schönen Grüßen aus Berlin,
Jörg Ohnheiser | Johanniterstrasse 4 | 10961 Berlin
030/30605744   |   0151/10860477

**Comment by g012** [comment]
I've just got it working. Yet I find it misleading to provide a zip and say "If you want to get started fast, download Silex as an archive and extract it", and below a second paragraph suggesting to use composer to get silex instead only "If you want more flexibility". You should change the documentation and make it clear we need to use composer or "every kind of PSR-0 autoloader" to get and use the Silex. The zip/tar alone won't help at all.

Sorry but for someone like me who only needs a website once in a blue moon, I have no idea what a PSR-0 autoloader is nor do I want to spend time to learn it. I was expecting to drop the content of the archive and get the index.php script working instantly, instead I had to check this page, go back to the doc about composer, go on its website, and make sure it didn't install crap everywhere but just in the current dir before finally deciding to give it a try. Not very intuitive for occasionals like me.

**Comment by g012** [comment]
Well I got on this page looking for a solution about this for another project, just noticed. It's the doc from that project which is misleading then, sorry about that.

**Comment by troindx** [comment]
Composer can be a very useful tool, but sometimes it just adds a lot of complexness where there is no need to, and it has also been proven by a lot of scientific experiments that using composer leads to cancer in the anus.

Be that as it may, i'd suggest a small package where a stable functioning version of the file is included "out of the box", so that composer isn't needed. cos it could be useful for people who need this for something small, and don't require that much ammount.

it's just a suggestion, suggestions are free of charge :) keep the good work.

**Comment by postalservice14** [comment]
Back to the original issue.  In order to use the demo's and tests, composer is required.  Demo's are just used to __demonstrate__ the capabilities of the library.  Although you can use the library without composer, it is not the recommended approach and therefore the examples and tests require it.

@troindx please read the [CoC](https://github.com/php-amqplib/php-amqplib/blob/master/CODE_OF_CONDUCT.md) and keep your comments/suggestions constructive.

**Comment by levhita** [comment]
I'm just going to try to be constructive (altought I really really hate composer), there is really to point to redirect people to install composer, when the actual dependency is "add any compatible PSR-0 autoloader",  such compatible loader could be provided out of the box, or simply as part of the documentation(10 lines of code is not much), which in turn could provide the suggestion to user composer too if wished.

To take composer as a kind of standarized default is the problem here, PSR-O IS AN STANDARD, Composer is only a package manager that some people like to use.

**Comment by kheldaroz** [comment]
in my case the issue was with the Mac using its own internal php not the Mamp PHP

**Comment by troindx** [comment]
I had the same problem

**Comment by herbertgatchalian** [comment]
hi, sorry i;m stupid and new to this. but i was able to use composer and install everything. 

problem is when i try to run the samples, i'm getting this error 

"Fatal error: Class 'Infusionsoft\Infusionsoft' not found in D:\htdocs\infusion\samples\addWithDupCheck.php on line 7"

**Comment by ronator** [comment]
I simply can't even just install composer - why are such things happening to stable branch?

**Comment by michaelklishin** [comment]
@ronator we can't recommend anything based on "can't even just install composer". This is not a support forum. If you have questions, please post them to rabbitmq-users, our public mailing list.

Usually any obvious installation issue is reported multiple times a day. This is not something we hear about and I personally had to go through the RabbitMQ PHP tutorials that use this client and it worked just fine with both 2.5.x and 2.6.x versions.
