### ISSUE TITLE
Long phpamqplib.DEBUG: Queue message processed logs before throwing fwrite

### ISSUE THREAD

**Issue by echonox** [php-amqplib/php-amqplib#623]
We use Symfony with the RabbitMqBundle, but very frequently we get:

```
phpamqplib.ERROR: fwrite(): send of 21 bytes failed with errno=104 Connection reset by peer
```

Along that we get HUGE phpamqplib.DEBUG: Queue message processed lines, and  doctrine.DEBUG lines, at one occasion it throw thousand and thousand of lines, which were going for a FULL DAY with more than 20.000 lines about it, and at the end a single error about fwrite()

My Questions are:
1. Why this long long and lots of debug logs happen when debugging is disabled at symfony?
2. Why the error happens in first place? We tried everything from the suggestions but nothing solved, except for prefetch count, can you give explanation how this solves the issue?
3. How can we prevent/disable this logs?

[php-623-debug.txt](https://github.com/php-amqplib/php-amqplib/files/2592901/php-623-debug.txt)

**Comment by lukebakken** [comment]
GitHub allows you to attach files to issues and comments. Rather than pasting a "wall of text", please use this feature next time.

> Why this long long and lots of debug logs happen when debugging is disabled at symfony?

This could be an issue with symfony. I don't have any control over how that library interacts with this one. If you can provide a _complete, runnable_ code sample that demonstrates this, I may be able to figure it out.

> Why the error happens in first place? We tried everything from the suggestions but nothing solved, except for prefetch count, can you give explanation how this solves the issue?

What other suggestions did you try? That would be very helpful for me to know.

Most likely, the `fwrite` error occurred because RabbitMQ closed the connection due to a missed heartbeat. You will see this in the RabbitMQ logs.

Prefect could have fixed this by allowing your code time to send the necessary heartbeats. This library is single-threaded (as necessary because it's PHP) and it is very easy for your code to do enough work to keep this library from being able to send a heartbeat. Prefetch will limit the number of messages RabbitMQ sends to your code at once.

> How can we prevent/disable this logs?

See my first answer. I will re-open this issue if you follow up with something I can work with. Thanks.
