### ISSUE TITLE
yii queue/listen No "message_id" property

### ISSUE THREAD

**Issue by Hutao-Final-error** [php-amqplib/php-amqplib#625]
![image](https://user-images.githubusercontent.com/12293460/48773775-59ad1400-ed03-11e8-8ada-4092d0729033.png)

I don't know why.
please tell me .  Thanks
![image](https://user-images.githubusercontent.com/12293460/48773874-9973fb80-ed03-11e8-99db-c30df258de4d.png)

**Comment by lukebakken** [comment]
This line is throwing the exception: [link](https://github.com/yiisoft/yii2-queue/blob/cbe860e13bcbc19e4d74b988fc32a3cb52af03e8/src/drivers/amqp/Queue.php#L67)

The `yii2-queue` library expects the message to have a `message_id` property but this is optional in AMQP. You can make sure that your messages always have this property as a workaround.

I just noticed that you filed this issue - yiisoft/yii2-queue#291. In the future, if you file issues in multiple GitHub repositories or projects *please* link them together. Had I known about that issue it would have saved me the time I spent investigating.

Since this library and many others that you use are maintained by volunteers, you should do whatever you can to save time for these people.

**Comment by Hutao-Final-error** [comment]
Ok, thank you very much
