### ISSUE TITLE
Duplicate call to AbstractIO::connect() during reconnecting (AbstractConnection::reconnect())

### ISSUE THREAD

**Issue by programmer512** [php-amqplib/php-amqplib#626]
php-amqplib version: 2.8.1

I noticed that 2 calls performed to AbstractIO::connect() when doing reconnecting (AbstractConnection::reconnect()).

1) First call is from AbstractIO::reconnect() ( $this->connect(); )
2) Second call is from AbstactConnection::connect() ( $this->getIO()->connect();)

**Comment by lukebakken** [comment]
This seems like a good issue to fix for version `2.9.0`. It would assist us greatly to have the following -

* Instructions on how to reproduce
* Code to reproduce, even if it's just a link to something in the [`demo`](https://github.com/php-amqplib/php-amqplib/blob/master/demo/connection_recovery_consume.php) directory

The less that this project's maintainers have to do to observe what you report the better, because we can then focus on fixing the issue.

**Comment by programmer512** [comment]
@lukebakken , checked  -- seems fine. thank you
