### ISSUE TITLE
Please, publish your OpenPGP key

### ISSUE THREAD

**Issue by DavidPrevot** [php-amqplib/php-amqplib#654]
Hi,

The tags of this repository seem signed for over a year, thanks! Unfortunately, the key used (E4A37A5B42627911600F3F81B707DD932540186E) does not seem to be public, which makes it difficult to verify the signatures. I finally managed to find it [online](https://keybase.io/krakken) but it is needlessly hard to find.

Could you please push your public key on the key servers network? It would also be nice if your key were signed by other people in order to make it in the [web of trust](https://pgp.cs.uu.nl/)

Thanks in advance.

**Comment by lukebakken** [comment]
Thanks for using this library.

You're the first person to bring this to my attention for any of the open-source software that I maintain. Apparently people don't care about the PGP signature of the tags. Since you've "found" the information on keybase, I'll consider that adequate until at least one other person brings this to my attention.
