### ISSUE TITLE
how to get Consumer Cancel Notify

### ISSUE THREAD

**Issue by zhenzhenwangdd01** [php-amqplib/php-amqplib#704]
when the cosumer is canceled by server for some reasons....how can i receive the consumer cancel notify??

**Comment by ramunasd** [comment]
Hi @zhenzhenwangdd01 do You know what type of network packet it is?

**Comment by zhenzhenwangdd01** [comment]
> Hi @zhenzhenwangdd01 do You know what type of network packet it is?

HI , its tcp

**Comment by ramunasd** [comment]
IMHO it is always TCP :) What I ask is RabbitMQ data protocol packet type, some of them can be seen here 
https://github.com/php-amqplib/php-amqplib/blob/master/PhpAmqpLib/Wire/Constants091.php

Full spec can be found here:
https://www.rabbitmq.com/resources/specs/amqp0-9-1.pdf

**Comment by zhenzhenwangdd01** [comment]
oh... i think it is  "Basic.cancel" . 
now, when  rabbitmq-server send it to the client,the client seems konw nothing.
I hope my client konws what has happened when the rabbitmq-server sended "Basic.cancel" to it.

**Comment by ramunasd** [comment]
According to [1] broker can send `basic.cancel` _in the case of such unexpected consumer cancellations_. This library expects that as package `60,30` and invokes method `\PhpAmqpLib\Channel\AMQPChannel::basic_cancel_from_server()` which in turn throws exception `\PhpAmqpLib\Exception\AMQPBasicCancelException`.

So that exception is notification for You. Just catch it inside consumption loop and check for other queues. Something like:

```
while ($channel->is_consuming()) {
    try {
        $channel->wait();
    } catch(AMQPBasicCancelException $exception) {
        continue;
    }
}
```

[1] https://www.rabbitmq.com/consumer-cancel.html
