### ISSUE TITLE
How to know When rabbitmq server get last heartbeat from client?

### ISSUE THREAD

**Issue by yuklia** [php-amqplib/php-amqplib#783]
Hello! 
I have long-running php-based consumer. 
When the connection is idle **or** consumer is working PHP stops to send heartbeat due to single-thread "limitation".

My solution is to write GO-based wrapper which will send heartbeat in a separate thread. But I need to define criteria: how to check **When was the last heartbeat from dedicated client on rabbitmq server.**

Looking forward to your opinions.

**Comment by lukebakken** [comment]
Hi @yuklia thanks for using this library.

You won't be able to use another language to send heartbeats because they are per-connection/per-channel in RabbitMQ. If your PHP application is blocking heartbeats, you need to do the work faster, or you can do the work in another PHP process, and when that is done, acknowledge the message.

Or, of course, you can re-write your consumer in another language. If you're planning to use go, I recommend this client library - https://github.com/streadway/amqp

There is no way to know when RabbitMQ last saw a heartbeat from a client. You _could_ modify RabbitMQ's source code to log this, but the information is not available by default.
