### ISSUE TITLE
PHP 8 compatibility 

### ISSUE THREAD

**Issue by Nickolay-Kehayov** [php-amqplib/php-amqplib#851]
Hello.
I would like to ask if there are any plans to update this library to support PHP8? 
At the moment, when i am testing my project for compatibility with PHP 8 from docker container 8.0.0RC5-apache ,i get the following deprecated errors:
Deprecated: Required parameter $routing_key follows optional parameter $redelivered in /my-project/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Helper/Protocol/Protocol091.php on line 662
Deprecated: Required parameter $exchange follows optional parameter $redelivered in /my-project/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Helper/Protocol/Protocol091.php on line 662
Deprecated: Required parameter $routing_key follows optional parameter $reply_text in /my-project/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Helper/Protocol/Protocol091.php on line 644
Deprecated: Required parameter $exchange follows optional parameter $ticket in /my-project/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Helper/Protocol/Protocol091.php on line 516

and many others similar to those. 

Thank you for your time and effort.

**Comment by ramunasd** [comment]
This question was already answered #846

**Comment by raveren** [comment]
Please show some respect for the users and leave one of the issues open, or just denote that the lib is not compatible with php8 somewhere - anywhere, currently there's no mention of it on the internet except in the closed issues!

**Comment by lukebakken** [comment]
> denote that the lib is not compatible with php8 somewhere

This _free software_ is open source. Please by all means open a pull request to update the documentation, `composer.json`, or some other file to make note of PHP8. Better yet, make the compatibility changes yourself and we will gladly review them!

@ramunasd and I maintain this library when we can but are usually busy with work that *pays* us.

I'm assuming this line could be changed to set an upper limit for the PHP version:

https://github.com/php-amqplib/php-amqplib/blob/master/composer.json#L32

**Comment by ramunasd** [comment]
We respect all our users :) that's why we are trying to keep this library stable as much as possible. And we promise any support only when we are 100% sure that all things goes fine on specific PHP versions.

Composer constraints does not restrict anyone to install and use this library on PHP8. There is no reported functional issues or evidence that this thing cannot work on PHP8, not yet :)

**Comment by raveren** [comment]
I'm testing migration of several big codebases to PHP8, it's gonna be a slow rollout, but I will try to report here if the lib fully works with a simple `~E_DEPRECATED` or some other approach.

The reason I commented with a bit of frustration is I found it ironic to search google in all possible ways for why php-amqplib doesn't run on PHP8 with _no results_ and the first result would always say `The most widely used PHP client for RabbitMQ` :)

Anyway, this is not my decision definitely, but instead of documenting the uncertain status in the readme it just seems creating a PHP8 open issue would make most sense.

Anyway, thanks for your hard work guys!

**Comment by robo2bobo** [comment]
I've tested php-amqplib with PHP8 and created a patch to fix the deprecation warnings: https://github.com/php-amqplib/php-amqplib/issues/860#issuecomment-752139275

**Comment by lukebakken** [comment]
@sbacelic @Nickolay-Kehayov @raveren 

Please take the time to test `v3.0.0-rc1` in your environment and report back if issues are found:

https://groups.google.com/g/rabbitmq-users/c/ktkiQ9slrME

https://packagist.org/packages/php-amqplib/php-amqplib#3.0.0-rc1

**Comment by lukebakken** [comment]
Latest RC is https://packagist.org/packages/php-amqplib/php-amqplib#v3.0.0-rc2

The above should ship as `3.0.0` this week.
