### ISSUE TITLE
AMQPChannel.close() is hanging when connection is in blocking status

### ISSUE THREAD

**Issue by Onalu** [php-amqplib/php-amqplib#88]
Hi,

RabbitMQ server puts connection into blocking state if memory watermark alarm is true. In this state RMQ blocks publishing and basic_publish() method returns false. But after this if I try to close channel it will be hanging while waiting ''channel.close_ok' method. Passing a timeout value to the wait method called in AMQPChannel.close() solves this problem but I am not sure whether it is a good idea or bad. The timeout which is set in the AMQPStreenConnection is not working.

**Comment by mszabo-wikia** [comment]
Hi @videlalvaro , are you sure this should be expected behavior? The official Java client for RabbitMQ, for instance, specifies a timeout for the channel close operation—see https://github.com/rabbitmq/rabbitmq-java-client/pull/46 . I think it'd be worthwhile if the PHP client would allow to set a timeout for this operation as well, because it's important from a resiliency perspective to allow clients to fail-fast in case the server is unavailable due to an alarm or other outage. Otherwise the lack of an explicit timeout will rapidly exhaust client resources.

**Comment by lukebakken** [comment]
@mszabo-wikia - we'd be happy to review a PR for this. Thanks!
